Pooja Dev : Course List | Course Details
ArcherInfotechAndroid/Android_App_Projects pull request #3
Opened 2024-09-27 08:57 UTC by poojaapatil2117

**Course List**

1. Adaptor 
       - extends RecyclerView.Adapter<CourceAdaptor.CourceViewHolder>
      
2. Modal
      Create Course Class where I Set getters and Setters.

3. Listener
      - creating one Interface in this package i.e ItemClickListner when we click on an item it will go to a detailed page of Cource

4. Cource List
     Create a List of Different Courses Using RecyclerView.
 
 

**Cource Details**

This page provides detailed information about the course.

- Name of Course.
- Course Curriculum
- Modes Of Training
- Instructor Info
- Payment Button and Cancel Button.

2024-09-27 09:02 UTC, PGW0808 commented
Approved

2024-09-27 09:42 UTC, ArcherInfotechInhouseTraining commented on TutionApp/.idea/misc.xml
>  <project version="4">
add <?xml version="1.0" encoding="UTF-8"?>

2024-09-27 09:46 UTC, ArcherInfotechInhouseTraining requested changes
make changes and pull request for merge

2024-09-27 09:46 UTC, ArcherInfotechInhouseTraining commented on TutionApp/.idea/misc.xml
>  <project version="4">
add <?xml version="1.0" encoding="UTF-8"?> as first line

2024-09-28 06:04 UTC, poojaapatil2117 reviewed
Changes Done.

2024-09-28 10:05 UTC, closed without merging